name: Build and Run C# Application on Excel File Push

on:
  push: # Trigger the workflow on push events
    branches:
      - main # Adjust this based on your branch
    paths:
      - '**.xlsx' # Detect any Excel file changes in the repository

jobs:
  run-task-automation:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout ZohoTaskTemplates repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Identify changed Excel files
        run: |
          git diff --name-only HEAD^ HEAD > changed_files.txt
          cat changed_files.txt

      - name: Set file path
        id: setpath
        run: |
          FILE=$(grep -E '\.xlsx$' changed_files.txt | head -n 1)
          echo "::set-output name=filepath::$FILE"

      - name: Clone GRL-Zoho-Insights repo
        run: |
          git clone https://$GITHUB_ACTOR:${{ secrets.REPO_TOKEN }}@github.com/chandrashekhar54/GRL-Zoho-Insights.git

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y dotnet-sdk-6.0

      - name: Run C# application with Excel file
        run: |
          cd GRL-Zoho-Insights
          dotnet build
          dotnet run -- "${{ steps.setpath.outputs.filepath }}"
