name: Build and Run C# Application on Excel File Push

on:
  push: # Trigger the workflow on push events
    branches:
      - main # Adjust this based on your branch
    paths:
      - '**.xlsx' # Detect any Excel file changes in the repository

jobs:
  build-and-run:
    runs-on: ubuntu-latest
    env: 
      wrkng-dir: GRL-Zoho-Insights

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Checkout GRL-Zoho-Insights
      uses: actions/checkout@v3
      with:
          ref: TaskCreate
          repository: chandrashekhar54/GRL-Zoho-Insights
          path: ${{env.wrkng-dir}}
          token: ${{ secrets.REPO_TOKEN }}

    - name: Set up .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '7.0.x' # Adjust the version based on your project
        
    - name: Check which Excel file was changed
      id: detect-excel-file
      run: |
        echo "Modified files:"
        git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep ".xlsx" || echo "No Excel files found"
        MODIFIED_FILES=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep ".xlsx")
        if [[ -n "$MODIFIED_FILES" ]]; then
          echo "Excel file(s) detected: $MODIFIED_FILES"
          echo "excel_file_path=$MODIFIED_FILES" >> $GITHUB_ENV
        else
          echo "No Excel files detected."
        fi

    - name: Restore NuGet packages
      run: dotnet restore GRL-Zoho-Insights/GRL-Zoho-Insights.csproj
      working-directory: ${{env.wrkng-dir}}

    - name: Run the C# application
      run: |
        echo "Running C# Application with Excel File Path: ${{ env.excel_file_path }}"
        dotnet run --project GRL-Zoho-Insights/GRL-Zoho-Insights.csproj -- "$excel_file_path"
      working-directory: ${{env.wrkng-dir}}
